/**
 * Shared SafetyContext — the cross-feature state that powers the Copilot
 * journey across /chatbot, /accidents-reports, and /strategy/plan-generator.
 *
 * The three flagship features run independently today, so each one stashes
 * a small slice of the user's intent here. Subsequent features can then
 * pre-fill industry/concern/plan inputs and offer "continue where you left
 * off" links without forcing the user to re-state context.
 */
import type { IndustrySlug } from "@/lib/industry-slugs";

export type CopilotScale = "small" | "medium" | "large";

/**
 * High-level concerns the user has expressed. These map to accident topics,
 * RAG search seeds, and plan-generator focus areas. Kept as a free-text
 * string array (not an enum) so we can capture novel phrases the user types
 * into the chatbot.
 */
export type CopilotConcern = string;

export type CopilotStepId = "chatbot" | "accidents-reports" | "plan-generator";

export interface CopilotPlanSnapshot {
  industry?: IndustrySlug;
  scale?: CopilotScale;
  fiscalYear?: number;
  templateId?: string;
  href?: string;
  generatedAt?: string;
  organizationName?: string;
}

export interface CopilotRecentQuery {
  query: string;
  source: CopilotStepId;
  at: number;
}

export interface CopilotProgressFlags {
  visitedChatbot: boolean;
  visitedAccidentsReports: boolean;
  visitedPlanGenerator: boolean;
  /** True once the plan generator has produced a preview URL */
  generatedPlan: boolean;
}

export interface SafetyContextState {
  /** Canonical accidents-reports slug (5 industries) */
  industry?: IndustrySlug;
  scale?: CopilotScale;
  /** Free-form keywords/topics the user keeps coming back to */
  keyConcerns: CopilotConcern[];
  /** Last 12 search/question strings across the 3 features */
  recentQueries: CopilotRecentQuery[];
  /** The latest plan generated by /strategy/plan-generator (if any) */
  activePlan?: CopilotPlanSnapshot;
  progress: CopilotProgressFlags;
  /** Last-touched feature (for "continue where you left off") */
  lastStep?: CopilotStepId;
  updatedAt: number;
}

export const SAFETY_CONTEXT_STORAGE_KEY = "anzen-copilot:safety-context:v1";
export const SAFETY_CONTEXT_MAX_QUERIES = 12;
export const SAFETY_CONTEXT_MAX_CONCERNS = 8;

export function createEmptySafetyContext(): SafetyContextState {
  return {
    industry: undefined,
    scale: undefined,
    keyConcerns: [],
    recentQueries: [],
    activePlan: undefined,
    progress: {
      visitedChatbot: false,
      visitedAccidentsReports: false,
      visitedPlanGenerator: false,
      generatedPlan: false,
    },
    lastStep: undefined,
    updatedAt: 0,
  };
}

/** Defensive parser: tolerates partial or malformed legacy payloads. */
export function normalizeSafetyContext(raw: unknown): SafetyContextState {
  const base = createEmptySafetyContext();
  if (!raw || typeof raw !== "object") return base;
  const obj = raw as Partial<SafetyContextState> & Record<string, unknown>;
  const next: SafetyContextState = {
    ...base,
    industry: isIndustrySlug(obj.industry) ? obj.industry : undefined,
    scale: isScale(obj.scale) ? obj.scale : undefined,
    keyConcerns: Array.isArray(obj.keyConcerns)
      ? obj.keyConcerns
          .filter((c): c is string => typeof c === "string" && c.trim().length > 0)
          .slice(0, SAFETY_CONTEXT_MAX_CONCERNS)
      : [],
    recentQueries: Array.isArray(obj.recentQueries)
      ? (obj.recentQueries as unknown[])
          .map((q) => {
            if (!q || typeof q !== "object") return null;
            const r = q as Partial<CopilotRecentQuery>;
            if (typeof r.query !== "string" || !isStepId(r.source)) return null;
            return {
              query: r.query.slice(0, 240),
              source: r.source,
              at: typeof r.at === "number" ? r.at : Date.now(),
            } satisfies CopilotRecentQuery;
          })
          .filter((q): q is CopilotRecentQuery => q !== null)
          .slice(0, SAFETY_CONTEXT_MAX_QUERIES)
      : [],
    activePlan: normalizePlan(obj.activePlan),
    progress: {
      visitedChatbot: Boolean(
        (obj.progress as Partial<CopilotProgressFlags> | undefined)?.visitedChatbot,
      ),
      visitedAccidentsReports: Boolean(
        (obj.progress as Partial<CopilotProgressFlags> | undefined)?.visitedAccidentsReports,
      ),
      visitedPlanGenerator: Boolean(
        (obj.progress as Partial<CopilotProgressFlags> | undefined)?.visitedPlanGenerator,
      ),
      generatedPlan: Boolean(
        (obj.progress as Partial<CopilotProgressFlags> | undefined)?.generatedPlan,
      ),
    },
    lastStep: isStepId(obj.lastStep) ? obj.lastStep : undefined,
    updatedAt: typeof obj.updatedAt === "number" ? obj.updatedAt : 0,
  };
  return next;
}

function normalizePlan(value: unknown): CopilotPlanSnapshot | undefined {
  if (!value || typeof value !== "object") return undefined;
  const v = value as Partial<CopilotPlanSnapshot>;
  if (!v.industry && !v.templateId && !v.href) return undefined;
  return {
    industry: isIndustrySlug(v.industry) ? v.industry : undefined,
    scale: isScale(v.scale) ? v.scale : undefined,
    fiscalYear: typeof v.fiscalYear === "number" ? v.fiscalYear : undefined,
    templateId: typeof v.templateId === "string" ? v.templateId.slice(0, 64) : undefined,
    href: typeof v.href === "string" && v.href.startsWith("/") ? v.href.slice(0, 1024) : undefined,
    generatedAt: typeof v.generatedAt === "string" ? v.generatedAt.slice(0, 32) : undefined,
    organizationName:
      typeof v.organizationName === "string" ? v.organizationName.slice(0, 64) : undefined,
  };
}

function isIndustrySlug(v: unknown): v is IndustrySlug {
  return (
    v === "construction" ||
    v === "manufacturing" ||
    v === "transport" ||
    v === "healthcare" ||
    v === "service"
  );
}

function isScale(v: unknown): v is CopilotScale {
  return v === "small" || v === "medium" || v === "large";
}

function isStepId(v: unknown): v is CopilotStepId {
  return v === "chatbot" || v === "accidents-reports" || v === "plan-generator";
}
