/**
 * 機能ポートフォリオの正本。
 *
 * 「ページが存在する」ことと「主力サービスとして案内する」ことを分離し、
 * ナビゲーション、横断検索、自動化サンプル集約から同じ Tier・役割・運用状態を参照する。
 * Tier 4 は URL/SEO の保全方針を記録するため残すが、検索・主要導線には射影しない。
 */

export const FEATURE_TIERS = [1, 2, 3, 4] as const;
export type FeatureTier = (typeof FEATURE_TIERS)[number];

export const FEATURE_PORTFOLIO_ROLES = [
  "flagship",
  "practical-support",
  "automation-sample",
  "integrated-or-hidden",
] as const;
export type FeaturePortfolioRole = (typeof FEATURE_PORTFOLIO_ROLES)[number];

export const FEATURE_OPERATIONAL_STATUSES = [
  "operational",
  "limited",
  "preparing",
  "quarantined",
  "redirected",
  "private",
] as const;
export type FeatureOperationalStatus =
  (typeof FEATURE_OPERATIONAL_STATUSES)[number];

export const FEATURE_SEARCH_GROUPS = [
  "law",
  "accident",
  "chemical",
  "qualification",
  "education",
  "kyt",
  "tool",
  "automation-sample",
] as const;
export type FeatureSearchGroup = (typeof FEATURE_SEARCH_GROUPS)[number];

export type FeatureIndexability =
  | "index"
  | "noindex-follow"
  | "redirect"
  | "not-found"
  | "private"
  | "mixed";

export const FEATURE_TIER_LABELS: Record<FeatureTier, string> = {
  1: "Tier 1 主力機能",
  2: "Tier 2 実務支援",
  3: "Tier 3 自動化サンプル",
  4: "Tier 4 統合・非表示",
};

export const FEATURE_ROLE_LABELS: Record<FeaturePortfolioRole, string> = {
  flagship: "主力機能",
  "practical-support": "実務支援",
  "automation-sample": "自動化サンプル",
  "integrated-or-hidden": "統合・非表示",
};

export const FEATURE_STATUS_LABELS: Record<
  FeatureOperationalStatus,
  string
> = {
  operational: "運用中",
  limited: "制限付き",
  preparing: "準備中",
  quarantined: "公開隔離",
  redirected: "統合済み",
  private: "非公開",
};

export const FEATURE_SEARCH_GROUP_LABELS: Record<
  FeatureSearchGroup,
  string
> = {
  law: "法令",
  accident: "事故",
  chemical: "化学物質",
  qualification: "資格",
  education: "教育",
  kyt: "KYT",
  tool: "ツール",
  "automation-sample": "自動化サンプル",
};

export interface AutomationSampleProfile {
  /** 一覧カードに表示するサンプルだけ true。集約ページ自身は false。 */
  displayInGallery: boolean;
  maturityLabel: "サンプル" | "試作";
  canDo: readonly string[];
  cannotDo: readonly string[];
  requiredSettings: readonly string[];
  dataHandling: string;
}

export interface FeaturePortfolioEntry {
  id: string;
  label: string;
  route: string;
  relatedRoutes?: readonly string[];
  currentRole: string;
  tier: FeatureTier;
  role: FeaturePortfolioRole;
  reason: string;
  userValue: string;
  dataSource: string;
  aiApiIntegration: string;
  operationalStatus: FeatureOperationalStatus;
  operationalReadiness: string;
  seoValue: string;
  safetyRisk: string;
  navPlacement: string;
  indexability: FeatureIndexability;
  redirectCanonical: string;
  automationSamplePotential: string;
  action: string;
  acceptanceCriteria: string;
  searchGroup: FeatureSearchGroup;
  searchable: boolean;
  keywords: readonly string[];
  automationSample?: AutomationSampleProfile;
}

/**
 * 基準日 2026-07-30 JST のコード・公開状態に基づく分類。
 * 「AI/API integration」は実装済みの接続だけを記述し、予定機能を実装済みとは扱わない。
 */
export const FEATURE_PORTFOLIO = [
  // Tier 1: 主力機能
  {
    id: "today-safety",
    label: "今日の安全",
    route: "/risk",
    currentRole: "地域・作業別の朝礼入口",
    tier: 1,
    role: "flagship",
    reason: "毎日の利用頻度が高く、気象・作業・朝礼を一つの行動へまとめる入口だから。",
    userValue: "地域と作業を選び、その日の注意点を朝礼前に短時間で確認できる。",
    dataSource: "気象庁等の公開情報、サイト内の作業別ルールと編集済み案内。",
    aiApiIntegration: "キー不要の気象データ取得とサイト内リスク情報を統合。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。取得不能時を「警報なし」と扱わない境界を維持。",
    seoValue: "現場気象・今日の安全・朝礼という継続検索需要がある。",
    safetyRisk: "予報や一般案内を現場固有の安全判断の代替にしない表示が必要。",
    navPlacement: "PC一次ナビ「今日の安全」、ホームの季節ヒーロー直後。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "主力機能のためサンプル扱いにしない。",
    action: "主CTAと現在状態を先に表示し、説明は段階表示へ移す。",
    acceptanceCriteria: "ホームと一次ナビから1クリック、取得状態と対象地域を常時表示。",
    searchGroup: "tool",
    searchable: true,
    keywords: ["今日の安全", "現場リスク", "朝礼", "現場気象", "作業別リスク"],
  },
  {
    id: "heat-hub",
    label: "熱中症対策",
    route: "/heat-illness-prevention",
    relatedRoutes: [
      "/heat-illness-prevention/slides",
      "/heat-illness-prevention/elearning",
    ],
    currentRole: "夏季の安全対策ハブ",
    tier: 1,
    role: "flagship",
    reason: "夏季の現場需要と緊急性が高く、WBGT・公的資料・対応導線を集約するから。",
    userValue: "暑さ指数、予防、異常時対応、公的資料の確認先を一か所で把握できる。",
    dataSource: "厚生労働省・環境省等の公的資料とキー不要の気象情報。",
    aiApiIntegration: "気象データ連携あり。医療・法務判断を生成AIで作らない。",
    operationalStatus: "limited",
    operationalReadiness: "外部承認前のため noindex,follow。公的資料を正本として公開。",
    seoValue: "季節需要は大きいが、承認完了までは検索流入を獲得しない。",
    safetyRisk: "緊急症状を軽く扱わず、119等の緊急導線と公的資料を優先する。",
    navPlacement: "夏季はホーム最上部とモバイルナビ。通常期は「今日の安全」配下。",
    indexability: "noindex-follow",
    redirectCanonical: "現在URLと自己canonicalを維持し、sitemap除外を継続。",
    automationSamplePotential: "主力安全情報のためサンプル扱いにしない。",
    action: "夏季版チワワと短い主CTAを置き、未監修境界を維持。",
    acceptanceCriteria: "hub・slides・e-learningの3ページが noindex,follow かつ sitemap非収載。",
    searchGroup: "education",
    searchable: true,
    keywords: ["熱中症", "WBGT", "暑さ指数", "夏季", "緊急時対応"],
  },
  {
    id: "law-ai-chat",
    label: "安衛法AIチャット",
    route: "/chatbot",
    currentRole: "法令根拠候補の対話検索",
    tier: 1,
    role: "flagship",
    reason: "法令の入口として独自価値が高く、質問から条文・出典へ移動できるから。",
    userValue: "現場の言葉で質問し、確認すべき法令候補と一次資料への導線を得られる。",
    dataSource: "e-Gov取得スナップショットと確認済みの法令・通達データ。",
    aiApiIntegration: "生成AI自由回答は停止中。サイト内法令検索で根拠候補を返す。",
    operationalStatus: "limited",
    operationalReadiness: "根拠候補検索として公開。回答は一次資料で人が最終確認する。",
    seoValue: "安衛法の質問・条文確認という明確な検索意図を持つ。",
    safetyRisk: "法的判断の断定、個人情報入力、緊急相談の誤受付を防ぐ必要がある。",
    navPlacement: "PC一次ナビ「法令AI」、モバイル一次ナビ。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "中核検索機能のためサンプル扱いにしない。",
    action: "質問チップと入力を先に置き、「使い方と限界」は details に集約。",
    acceptanceCriteria: "一次ナビから1クリック、PII禁止・119・一次資料確認を冒頭で明示。",
    searchGroup: "law",
    searchable: true,
    keywords: ["安衛法AI", "法令質問", "条文", "労働安全衛生法", "根拠候補"],
  },
  {
    id: "law-search",
    label: "法令検索",
    route: "/law-search",
    currentRole: "安衛法関連法令の全文検索",
    tier: 1,
    role: "flagship",
    reason: "一次資料へ到達するタスク完遂度が高く、AI回答の検証先になるから。",
    userValue: "条文番号・語句から関連法令を直接探せる。",
    dataSource: "e-Gov等から取得した法令スナップショット。",
    aiApiIntegration: "サイト内全文検索。外部生成AIへの入力送信なし。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。対象時点と原文確認導線を表示。",
    seoValue: "条文名・条番号・義務内容の継続需要が高い。",
    safetyRisk: "更新時点の取り違えを避け、公式原文を正本と明示する。",
    navPlacement: "「法令AI」メニュー内の主力リンク。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "公式情報検索の主力なのでサンプル扱いにしない。",
    action: "検索欄と分野チップをファーストビューへ固定。",
    acceptanceCriteria: "ホームまたは一次メニューから1クリック、検索結果から公式原文へ到達可能。",
    searchGroup: "law",
    searchable: true,
    keywords: ["法令検索", "条文検索", "安衛法", "安衛則", "全文検索"],
  },
  {
    id: "law-navi",
    label: "法令ナビ",
    route: "/law-navi",
    currentRole: "分野・現場ことばから条文へ進むナビ",
    tier: 1,
    role: "flagship",
    reason: "専門語を知らない利用者でも法令原文へ到達でき、教育価値が高いから。",
    userValue: "作業や俗称から関連条文を探し、原文とやさしい説明を並べて確認できる。",
    dataSource: "法令スナップショット、編集済みの現場ことば索引。",
    aiApiIntegration: "サイト内索引・関連付け。外部AIへの送信なし。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。原文とサイト解説を区別。",
    seoValue: "現場語と法令語の橋渡しとしてロングテール価値がある。",
    safetyRisk: "やさしい言い換えを法令原文と誤認させない。",
    navPlacement: "「法令AI」メニュー内。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "主力情報導線なのでサンプル扱いにしない。",
    action: "分野と現場語の選択を説明より先に表示。",
    acceptanceCriteria: "2クリック以内で条文原文へ到達し、情報種別が常時見分けられる。",
    searchGroup: "law",
    searchable: true,
    keywords: ["法令ナビ", "現場ことば", "条文原文", "法令体系"],
  },
  {
    id: "law-revisions",
    label: "安衛法改正",
    route: "/laws",
    currentRole: "法改正一覧",
    tier: 1,
    role: "flagship",
    reason: "施行日・対象者・今やることを継続更新でき、実務価値が高いから。",
    userValue: "最新改正の対象と期限を短時間で確認できる。",
    dataSource: "厚生労働省等の法令・告示・公表資料。",
    aiApiIntegration: "取得・要約補助はあっても、原文と編集解説を分離。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。施行日と出典を表示。",
    seoValue: "改正名・施行日・対応事項の時限性検索に強い。",
    safetyRisk: "法的義務、行政推奨、サイト提案を混同しない。",
    navPlacement: "「事故・法改正」メニューの主力リンク。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "更新型の主力情報機能として扱う。",
    action: "最新改正・施行日・対象者・今やることを4項目で先に提示。",
    acceptanceCriteria: "一次メニューから1クリック、全カードに施行日と出典を表示。",
    searchGroup: "law",
    searchable: true,
    keywords: ["安衛法改正", "法改正", "施行日", "今やること"],
  },
  {
    id: "official-circulars",
    label: "通達・法令ニュース",
    route: "/circulars",
    currentRole: "行政通達・判例の検索",
    tier: 1,
    role: "flagship",
    reason: "公式情報の収集力と更新性がサイトの信頼を直接支えるから。",
    userValue: "通達番号・分野・日付から公的な運用情報を探せる。",
    dataSource: "厚生労働省等の公式通達・公表資料。",
    aiApiIntegration: "サイト内検索・関連付け。出典原文を正本とする。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。出典・取得日・情報種別を表示。",
    seoValue: "通達番号や制度名の専門検索に継続価値がある。",
    safetyRisk: "サイト解説を行政の公式見解と誤認させない。",
    navPlacement: "「事故・法改正」メニュー内。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "公式情報収集の主力なのでサンプル扱いにしない。",
    action: "新着・分野・検索・出典を冒頭へ集約。",
    acceptanceCriteria: "一次メニューから1クリック、各項目から公式出典へ到達可能。",
    searchGroup: "law",
    searchable: true,
    keywords: ["通達", "基発", "法令ニュース", "行政通達"],
  },
  {
    id: "whats-new",
    label: "安全情報の新着",
    route: "/whats-new",
    currentRole: "法改正・事故・通達・報道の統合フィード",
    tier: 1,
    role: "flagship",
    reason: "複数の更新情報を一つの短いフィードで追えるため、再訪価値が高いから。",
    userValue: "種別・日付・出典・重要度を見分けながら新着を確認できる。",
    dataSource: "公的発表、報道RSS、サイト内の更新済みコンテンツ。",
    aiApiIntegration: "キー不要のRSS等を取得し、情報種別を保持して統合。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。公式・報道・編集情報を区別。",
    seoValue: "更新情報のハブとして内部回遊と鮮度シグナルを支える。",
    safetyRisk: "報道由来を公式事故データと誤認させない。",
    navPlacement: "「事故・法改正」メニューとホーム新着フィード。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "更新型の主力情報機能として扱う。",
    action: "事故・法改正・教育の新着を一つの短いフィードに統合。",
    acceptanceCriteria: "種別・日付・出典・重要度を一覧で判別できる。",
    searchGroup: "accident",
    searchable: true,
    keywords: ["新着情報", "安全ニュース", "更新情報", "速報", "RSS"],
  },
  {
    id: "chemical-ra",
    label: "化学物質リスクアセスメント",
    route: "/chemical-ra",
    currentRole: "SDS・作業条件の入力整理支援",
    tier: 1,
    role: "flagship",
    reason: "CAS・SDS・作業条件から公式評価へつなぐ実務タスクが明確だから。",
    userValue: "不足情報を整理し、CREATE-SIMPLEで最終評価する準備ができる。",
    dataSource: "公的化学物質データ、利用者が確認したSDS・作業条件。",
    aiApiIntegration: "サイト内DB照合。公式評価ロジックの代替は行わない。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。CAS・SDS確認と公式ツールへの最終確認を必須表示。",
    seoValue: "化学物質名・CAS・SDS・RAの高い実務検索需要がある。",
    safetyRisk: "物質同定やばく露評価を断定せず、SDS・専門家・公式ツールを優先する。",
    navPlacement: "PC一次ナビ「化学物質」。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "安全判断に関わる主力機能なのでサンプル扱いにしない。",
    action: "5ステップの視覚フローと単一の開始CTAへ再編。",
    acceptanceCriteria: "一次ナビから1クリック、CAS・SDS・公式最終確認を全結果で表示。",
    searchGroup: "chemical",
    searchable: true,
    keywords: ["化学物質RA", "SDS", "CAS番号", "CREATE-SIMPLE", "リスクアセスメント"],
  },
  {
    id: "chemical-database",
    label: "化学物質検索",
    route: "/chemical-database",
    currentRole: "CAS・物質名による化学物質DB検索",
    tier: 1,
    role: "flagship",
    reason: "公式データとの接続が強く、化学物質RAの起点になるから。",
    userValue: "CAS番号・物質名から確認対象を絞り、RAへ進める。",
    dataSource: "厚生労働省・経済産業省等の公的オープンデータ。",
    aiApiIntegration: "サイト内統合検索。外部生成AIへの送信なし。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。出典と対象時点を表示。",
    seoValue: "物質名・CAS番号の具体検索需要が大きい。",
    safetyRisk: "同名異物質を避けるためCASとSDS記載名を併用する。",
    navPlacement: "「化学物質」メニューの主力リンク。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "公的データ検索の主力なのでサンプル扱いにしない。",
    action: "検索入力と出典状態を説明より先に表示。",
    acceptanceCriteria: "一次メニューから1クリック、結果からRAと公的出典へ到達可能。",
    searchGroup: "chemical",
    searchable: true,
    keywords: ["化学物質検索", "CAS検索", "GHS", "SDS情報"],
  },
  {
    id: "accident-news",
    label: "労災事故ニュース",
    route: "/accident-news",
    currentRole: "公表事実・匿名の重大災害情報検索",
    tier: 1,
    role: "flagship",
    reason: "公式データ・報道を区別して事故から学ぶ主力情報機能だから。",
    userValue: "新着、分野、事故型、起因物から事例を探し、再発防止の入口にできる。",
    dataSource: "厚生労働省等の公表データと、区別表示した報道由来情報。",
    aiApiIntegration: "検索・分類・関連事故導線。情報種別を保持。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。データセット単位の出典と個別追跡の限界を表示。",
    seoValue: "事故型・業種・原因別の高い検索需要がある。",
    safetyRisk: "報道、速報集計、確定個票を混同しない。",
    navPlacement: "「事故・法改正」メニューの主力リンク。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "中核データ機能なのでサンプル扱いにしない。",
    action: "新着・分野・検索・絞り込み・出典を最初に表示。",
    acceptanceCriteria: "一次メニューから1クリック、全結果で出典区分を判別可能。",
    searchGroup: "accident",
    searchable: true,
    keywords: ["労災事故", "重大災害", "事故ニュース", "死亡災害", "出典区分"],
  },
  {
    id: "official-resources",
    label: "教育資料",
    route: "/resources",
    relatedRoutes: ["/resources/mlit"],
    currentRole: "省庁の安全衛生資料ライブラリ",
    tier: 1,
    role: "flagship",
    reason: "公的資料への到達性と出典の明確さが教育・信頼性の基盤になるから。",
    userValue: "分野や発行元から現場で使う公的資料を探せる。",
    dataSource: "厚生労働省・国土交通省等の公開資料と出典URL。",
    aiApiIntegration: "サイト内分類・検索。資料本文を生成AIで置換しない。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。出典・発行元・確認日を表示。",
    seoValue: "安全教育資料・リーフレットの検索需要と回遊価値がある。",
    safetyRisk: "古い版や非公式資料を現行の正本と誤認させない。",
    navPlacement: "「全機能一覧」の「学ぶ・資格」分類。",
    indexability: "index",
    redirectCanonical: "現在URL群を維持し、各ページを自己canonical。",
    automationSamplePotential: "教育の主力情報機能として扱う。",
    action: "今学ぶ・所要時間・対象者・分野を先に表示。",
    acceptanceCriteria:
      "ホームから「全機能一覧」を経由して2クリック以内、資料ごとに発行元・出典・確認日を表示。",
    searchGroup: "education",
    searchable: true,
    keywords: ["教育資料", "安全衛生資料", "厚労省リーフレット", "研修資料"],
  },
  {
    id: "education-certification",
    label: "安全系資格",
    route: "/education-certification",
    currentRole: "特別教育・技能講習・作業主任者の確認DB",
    tier: 1,
    role: "flagship",
    reason: "作業条件から必要候補と根拠を確認する実務価値が高いから。",
    userValue: "資格制度の区分を見分け、作業に必要な候補と公式確認先を探せる。",
    dataSource: "労働安全衛生法令・行政資料と確認済みの資格データ。",
    aiApiIntegration: "条件検索と不足条件表示。受講可否を生成AIで断定しない。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。条件不足は判定保留として表示。",
    seoValue: "資格名・作業名・特別教育・技能講習の強い検索需要がある。",
    safetyRisk: "法定区分や就業制限を混同せず、最終確認先を示す。",
    navPlacement: "PC一次ナビ「学ぶ・資格」。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "資格情報の主力なのでサンプル扱いにしない。",
    action: "作業・資格名・教育区分の入口を視覚タブで先に表示。",
    acceptanceCriteria: "一次ナビから1クリック、区分・根拠・保留状態を判別可能。",
    searchGroup: "qualification",
    searchable: true,
    keywords: ["安全資格", "特別教育", "技能講習", "作業主任者", "就業制限"],
  },
  {
    id: "visual-kyt",
    label: "ビジュアルKYT",
    route: "/training/visual-ky",
    currentRole: "合成イラストを使う危険予知教育",
    tier: 1,
    role: "flagship",
    reason: "視覚で危険を学ぶ独自性、教育完遂度、朝礼利用価値が高いから。",
    userValue: "5分で危険箇所、理由、対策の優先順位、作業中止条件を学べる。",
    dataSource: "架空の学習用画像、確認済みの公的根拠、編集済み解説。",
    aiApiIntegration: "学習進行と関連教材連携。実在事故画像として扱わない。",
    operationalStatus: "operational",
    operationalReadiness: "15シナリオを公開運用中。架空の学習例と公的根拠を併記。",
    seoValue: "KYT・危険予知訓練・朝礼教育の検索需要と差別化がある。",
    safetyRisk: "合成教材を実事故記録と誤認させず、緊急場面を軽薄に扱わない。",
    navPlacement: "PC一次ナビ「KYT・実務」とホーム学習セクション。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "主力教育機能なのでサンプル扱いにしない。",
    action: "今日の問題・開始・完了・次の問題を学習コーチ型で案内。",
    acceptanceCriteria: "ホームまたは一次ナビから1クリック、架空の学習例と根拠を常時判別可能。",
    searchGroup: "kyt",
    searchable: true,
    keywords: ["ビジュアルKYT", "危険予知訓練", "今日の問題", "朝礼教育"],
  },
  {
    id: "automation-consult",
    label: "業務自動化相談",
    route: "/services/automation",
    currentRole: "料金・対応範囲・受付状態を示す受注導線",
    tier: 1,
    role: "flagship",
    reason: "収益化と個別業務改善への接続点だが、安全機能とは明確に区別できるから。",
    userValue: "対応範囲、料金目安、受付状態、必要資料を確認できる。",
    dataSource: "運営者が管理するサービス範囲・料金・受付状態。",
    aiApiIntegration: "メール相談は利用可能。相談本文をWebフォームや外部生成AIへ送信しない。",
    operationalStatus: "operational",
    operationalReadiness: "料金と対応範囲は公開。Webフォームは停止し、メール相談を受付中。",
    seoValue: "業務自動化・安全衛生講習・資料作成の商用検索意図がある。",
    safetyRisk: "Webフォームとメール相談を区別し、不要な個人情報入力欄を出さない。",
    navPlacement: "PC一次ナビの独立項目。ホーム中盤と終盤に明確な受注導線。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "サンプルの相談先だが、ページ自体は正式な料金・受付情報。",
    action: "受付状態をCTA直前に表示し、メール相談とWebフォームを明確に区別する。",
    acceptanceCriteria: "一次ナビから1クリック、provider未設定時はWebフォームを出さずメール相談へ案内する。",
    searchGroup: "tool",
    searchable: true,
    keywords: ["業務自動化相談", "安全業務効率化", "料金", "メール相談", "講習相談"],
  },

  // Tier 2: 実務支援
  {
    id: "qualification-finder",
    label: "資格finder",
    route: "/education-certification/finder",
    currentRole: "作業条件から資格候補を絞る補助ツール",
    tier: 2,
    role: "practical-support",
    reason: "資格DBのタスク完遂を補助するが、最終確認を単独で完結しないから。",
    userValue: "業種・作業・能力・役割から確認候補と不足条件を絞れる。",
    dataSource: "確認済みの資格データと法令根拠。",
    aiApiIntegration: "条件分岐検索。生成AI断定なし。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。条件不足は保留表示。",
    seoValue: "作業名から資格を探す具体検索意図がある。",
    safetyRisk: "候補を取得資格の確定と誤認させない。",
    navPlacement: "「学ぶ・資格」配下、主力資格ページから1クリック。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "主力DBの実務支援として扱う。",
    action: "主力資格ページから条件入力へ直結。",
    acceptanceCriteria: "ホームから2クリック以内、根拠と保留理由を表示。",
    searchGroup: "qualification",
    searchable: true,
    keywords: ["資格finder", "資格候補", "作業から探す", "必要資格"],
  },
  {
    id: "ky-paper",
    label: "KY用紙",
    route: "/ky/paper",
    relatedRoutes: ["/ky", "/ky/list", "/ky/workers", "/pdf"],
    currentRole: "危険予知活動表の作成・印刷",
    tier: 2,
    role: "practical-support",
    reason: "現場頻度は高いが、Visual KYTや今日の安全から使う実務帳票だから。",
    userValue: "現場条件と確認状態を残したKY用紙を作成・印刷できる。",
    dataSource: "利用者入力、端末内保存、確認済みの入力支援候補。",
    aiApiIntegration: "ブラウザ内入力支援・印刷。外部AIへの現場情報送信なし。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。未確認版と提出・承認状態を区別。",
    seoValue: "KY用紙・KYシートの継続検索需要がある。",
    safetyRisk: "入力候補を承認済みKYと誤認させず、現場確認を残す。",
    navPlacement: "「KYT・実務」配下、Visual KYTから関連導線。",
    indexability: "index",
    redirectCanonical: "現在URL群を維持。作成の正規入口は /ky/paper。",
    automationSamplePotential: "本番利用中の帳票であり、単なるデモ扱いにしない。",
    action: "作成CTAを先に置き、保存・印刷・説明を段階表示。",
    acceptanceCriteria: "ホームから2クリック以内、状態付き印刷と端末内保存の説明を維持。",
    searchGroup: "kyt",
    searchable: true,
    keywords: ["KY用紙", "KYシート", "危険予知活動表", "KY印刷"],
  },
  {
    id: "safety-diary",
    label: "安全工程打合せ書",
    route: "/safety-diary",
    relatedRoutes: ["/safety-diary/list"],
    currentRole: "作業・機械・災害・指示をまとめる現場帳票",
    tier: 2,
    role: "practical-support",
    reason: "主力情報機能から得た内容を日々の帳票へ落とす補助機能だから。",
    userValue: "各社の作業と安全指示を1枚に整理し、印刷・KY転記できる。",
    dataSource: "利用者入力、端末内保存、確認済みの候補データ。",
    aiApiIntegration: "ブラウザ内候補提案・帳票生成。外部AI送信なし。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。署名・承認の意味を過大表示しない。",
    seoValue: "安全工程打合せ書・安全衛生指示書の実務検索需要がある。",
    safetyRisk: "電子署名や法定承認を代替すると誤認させない。",
    navPlacement: "「KYT・実務」配下。",
    indexability: "index",
    redirectCanonical: "現在URL群を維持し、作成画面を自己canonical。",
    automationSamplePotential: "実務支援として提供し、自動化例からも紹介可能。",
    action: "新規作成と保存一覧を明確に分離。",
    acceptanceCriteria: "ホームから2クリック以内、印刷状態と確認状態を保持。",
    searchGroup: "tool",
    searchable: true,
    keywords: ["安全工程打合せ書", "安全衛生指示書", "工程打合せ", "帳票"],
  },
  {
    id: "signage",
    label: "安全サイネージ",
    route: "/signage",
    relatedRoutes: ["/signage/map"],
    currentRole: "朝礼・常時掲示ダッシュボード",
    tier: 2,
    role: "practical-support",
    reason: "日常利用価値は高いが、情報源となる今日の安全・事故・法改正を補助表示する機能だから。",
    userValue: "気象、リスク、事故、法改正を大画面でまとめて確認できる。",
    dataSource: "気象庁等の公開情報とサイト内更新情報。",
    aiApiIntegration: "キー不要の公開データ取得と自動更新。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。取得状態・地域・取得時刻を表示。",
    seoValue: "安全サイネージの導入意図はあるが、主に既存利用者の再訪機能。",
    safetyRisk: "取得不能を安全と誤認させず、緊急情報を装飾で妨げない。",
    navPlacement: "「KYT・実務」配下、全機能一覧。",
    indexability: "index",
    redirectCanonical: "現在URL群を維持。",
    automationSamplePotential: "実務支援として提供し、導入例としても説明可能。",
    action: "全画面開始を主CTAにし、設定は二次操作へ。",
    acceptanceCriteria: "ホームから2クリック以内、取得不能・古いデータを識別可能。",
    searchGroup: "tool",
    searchable: true,
    keywords: ["安全サイネージ", "朝礼モニター", "常時表示", "警報地図"],
  },
  {
    id: "heat-slides",
    label: "熱中症教育スライド",
    route: "/heat-illness-prevention/slides",
    currentRole: "承認前の熱中症教育補助",
    tier: 2,
    role: "practical-support",
    reason: "熱中症ハブを補助する教育形式で、外部承認前は主力教材にできないから。",
    userValue: "公的資料を参照しながら朝礼・教育の進行を補助できる。",
    dataSource: "公的資料と編集済みスライド。",
    aiApiIntegration: "外部生成AI live評価なし。",
    operationalStatus: "limited",
    operationalReadiness: "外部承認前。noindex,follow と sitemap除外を維持。",
    seoValue: "承認完了までは検索獲得対象にしない。",
    safetyRisk: "未承認教材を医学・法務の正本として扱わない。",
    navPlacement: "熱中症ハブ配下のみ。",
    indexability: "noindex-follow",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "教育支援だが自動化サンプルとは呼ばない。",
    action: "公的資料正本・承認状態・対象者を冒頭表示。",
    acceptanceCriteria: "noindex,follow、sitemap除外、公的資料導線を維持。",
    searchGroup: "education",
    searchable: true,
    keywords: ["熱中症スライド", "熱中症教育", "朝礼資料"],
  },
  {
    id: "heat-elearning",
    label: "熱中症eラーニング",
    route: "/heat-illness-prevention/elearning",
    currentRole: "承認前の熱中症学習補助",
    tier: 2,
    role: "practical-support",
    reason: "熱中症ハブの学習体験を補助するが、正式な法定教育を代替しないから。",
    userValue: "短い単元で熱中症の予防と異常時対応を復習できる。",
    dataSource: "公的資料と編集済み教材。",
    aiApiIntegration: "端末内学習進捗。外部生成AI送信なし。",
    operationalStatus: "limited",
    operationalReadiness: "外部承認前。noindex,follow と sitemap除外を維持。",
    seoValue: "承認完了までは検索獲得対象にしない。",
    safetyRisk: "修了を法定教育・資格・医学承認と誤認させない。",
    navPlacement: "熱中症ハブ配下のみ。",
    indexability: "noindex-follow",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "教育支援だが自動化サンプルとは呼ばない。",
    action: "所要時間・対象者・進捗・限界を先に表示。",
    acceptanceCriteria: "noindex,follow、sitemap除外、法定教育非代替を維持。",
    searchGroup: "education",
    searchable: true,
    keywords: ["熱中症eラーニング", "熱中症学習", "WBGT教育"],
  },
  {
    id: "accident-cases",
    label: "事故事例検索",
    route: "/accidents",
    currentRole: "編集再構成した事故事例の隔離中検索",
    tier: 2,
    role: "practical-support",
    reason: "関連事例の学習価値はあるが、個別一次資料照合が完了していないから。",
    userValue: "参考事例を事故型・業種から絞り、公式検索へ進める。",
    dataSource: "公開情報を編集部が再構成した混合データ。",
    aiApiIntegration: "サイト内検索・集計。一次資料照合を自動で保証しない。",
    operationalStatus: "limited",
    operationalReadiness: "隔離中ページとして noindex,follow。公式事故検索を優先案内。",
    seoValue: "照合完了までは検索獲得より誤認防止を優先。",
    safetyRisk: "編集事例を確定個票・公式記録と誤認させない。",
    navPlacement: "事故ニュースからの補助導線。一次ナビへ直接置かない。",
    indexability: "noindex-follow",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "データ品質上、自動化サンプルへ格上げしない。",
    action: "公式事故ニュースを主導線にし、隔離状態を明示。",
    acceptanceCriteria: "ホームから2クリック以内、公式・編集・架空の学習例を判別可能。",
    searchGroup: "accident",
    searchable: true,
    keywords: ["事故事例検索", "事故DB", "編集事例", "公式事故検索"],
  },
  {
    id: "global-search",
    label: "サイト内検索",
    route: "/search",
    currentRole: "全カテゴリの横断検索",
    tier: 2,
    role: "practical-support",
    reason: "主力・補助・サンプルを機能横断で見つける共通インフラだから。",
    userValue: "法令、事故、化学物質、資格、教育、KYT、ツール、サンプルを一括検索できる。",
    dataSource: "サイト内の公開可能な各データソース。",
    aiApiIntegration: "ブラウザ安全な索引を統合。検索語やPIIを外部AIへ送らない。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。情報種別・出典・検証状態を保持。",
    seoValue: "検索結果ページ自体より全ページの発見性と回遊を改善。",
    safetyRisk: "quarantine・幽霊URL・情報種別の欠落を防ぐ。",
    navPlacement: "ヘッダー検索、全機能メニュー、モバイルメニュー。",
    indexability: "noindex-follow",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "共通インフラでありサンプル扱いにしない。",
    action: "8検索群とTier・役割・運用状態のラベルを保持。",
    acceptanceCriteria: "全検索群あり、Tier 4混入0、幽霊URL0。",
    searchGroup: "tool",
    searchable: true,
    keywords: ["サイト内検索", "横断検索", "全機能検索", "検索"],
  },
  {
    id: "law-hierarchy",
    label: "法令体系マップ",
    route: "/law-hierarchy",
    currentRole: "法・政令・省令・告示の関係を示す補助図",
    tier: 2,
    role: "practical-support",
    reason: "法令検索・ナビの理解を補助する教育的な俯瞰機能だから。",
    userValue: "法令の階層と関連を視覚的に理解できる。",
    dataSource: "法令体系と編集済みの関係情報。",
    aiApiIntegration: "静的な関連表示。外部AI送信なし。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。公式原文へのリンクを備える。",
    seoValue: "法令体系の学習・理解検索に補助価値がある。",
    safetyRisk: "図解を法令原文の代替にしない。",
    navPlacement: "「法令AI」配下。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "法令学習の実務支援として扱う。",
    action: "法令ナビ・原文検索への次行動を固定。",
    acceptanceCriteria: "主力法令機能から1クリック、ホームから2クリック以内。",
    searchGroup: "law",
    searchable: true,
    keywords: ["法令体系", "法令マップ", "政令", "省令", "告示"],
  },
  {
    id: "glossary",
    label: "安全用語集",
    route: "/glossary",
    currentRole: "法令・現場用語の短い解説",
    tier: 2,
    role: "practical-support",
    reason: "専門語の理解を助け、法令・資格・教育へ回遊させる補助機能だから。",
    userValue: "分からない用語を短く理解し、関連する原文や機能へ進める。",
    dataSource: "法令原文と編集済み用語解説。",
    aiApiIntegration: "サイト内関連付け。外部AI送信なし。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。関連法令へリンク。",
    seoValue: "専門語のロングテール検索と内部回遊に価値がある。",
    safetyRisk: "短い定義を適用判断の代替にしない。",
    navPlacement: "「法令AI」「学ぶ・資格」配下。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "教育支援として扱う。",
    action: "用語検索を冒頭へ置き、関連先を明示。",
    acceptanceCriteria: "主力機能から1クリック、各用語に関連原文または関連機能あり。",
    searchGroup: "education",
    searchable: true,
    keywords: ["安全用語", "法令用語", "現場用語", "用語集"],
  },
  {
    id: "foreign-workers",
    label: "外国人労働者支援",
    route: "/foreign-workers",
    currentRole: "多言語安全教育と制度確認の入口",
    tier: 2,
    role: "practical-support",
    reason: "教育・資格・現場案内を対象者別に束ねる補助ハブだから。",
    userValue: "在留資格別の注意と多言語教材の公式確認先を探せる。",
    dataSource: "行政資料と編集済みの案内。",
    aiApiIntegration: "サイト内関連付け。機械翻訳を法的正本にしない。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。公式資料とサイト案内を区別。",
    seoValue: "外国人労働者・多言語安全教育の具体需要がある。",
    safetyRisk: "在留資格や法的義務を断定せず公式確認先を示す。",
    navPlacement: "「学ぶ・資格」配下と役割別入口。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "対象者別の実務支援として扱う。",
    action: "対象者・言語・必要行動を先に表示。",
    acceptanceCriteria: "ホームから2クリック以内、公式情報と翻訳支援を区別。",
    searchGroup: "education",
    searchable: true,
    keywords: ["外国人労働者", "多言語安全教育", "技能実習", "在留資格"],
  },
  {
    id: "treatment-work-balance",
    label: "治療と仕事の両立支援",
    route: "/treatment-work-balance",
    currentRole: "公的両立支援情報の実務ガイド",
    tier: 2,
    role: "practical-support",
    reason: "公的情報への案内価値はあるが、個別健康判断を提供しない補助ガイドだから。",
    userValue: "事業者・本人が両立支援の手順と公的様式を確認できる。",
    dataSource: "厚生労働省等の公的ガイドライン。",
    aiApiIntegration: "静的ガイド。健康情報を生成AIへ送らない。",
    operationalStatus: "limited",
    operationalReadiness: "一般案内として公開。個別プラン生成は隔離。",
    seoValue: "両立支援の制度・様式検索に価値がある。",
    safetyRisk: "医療判断・人事判断・個別健康相談を代替しない。",
    navPlacement: "全機能一覧または役割別入口。",
    indexability: "index",
    redirectCanonical: "ハブURLを維持。plan-builderは隔離。",
    automationSamplePotential: "個別健康情報を扱うためサンプル化しない。",
    action: "公的ガイドと相談先を先に表示。",
    acceptanceCriteria: "ホームから2クリック以内、健康情報入力やAI送信なし。",
    searchGroup: "education",
    searchable: true,
    keywords: ["治療と仕事", "両立支援", "主治医意見書", "復職支援"],
  },
  {
    id: "notifications",
    label: "通知・更新購読",
    route: "/notifications",
    currentRole: "画面通知・OS通知・RSSの設定",
    tier: 2,
    role: "practical-support",
    reason: "主力の新着情報を継続利用する補助機能で、実メール配信は準備中だから。",
    userValue: "利用可能な通知方法と停止中の配信方法を見分けて設定できる。",
    dataSource: "サイト内更新情報とブラウザ通知状態。",
    aiApiIntegration: "RSS・ブラウザ通知。実メール・実pushは実行しない。",
    operationalStatus: "limited",
    operationalReadiness: "画面・RSSは利用可。メール配信は準備中。",
    seoValue: "主に再訪・継続利用の価値。",
    safetyRisk: "通知未達を安全情報なしと扱わず、配信中と虚偽表示しない。",
    navPlacement: "メニュー内「新着・通知」。",
    indexability: "index",
    redirectCanonical: "現在URLを維持。newsletterは統合候補。",
    automationSamplePotential: "通知自動化の例として説明できるが、現在は実務支援。",
    action: "利用可能・準備中・端末依存を明確に分ける。",
    acceptanceCriteria: "ホームから2クリック以内、実メール・実pushなし。",
    searchGroup: "tool",
    searchable: true,
    keywords: ["通知設定", "RSS", "更新購読", "メール準備中"],
  },
  {
    id: "safety-goods",
    label: "安全グッズ",
    route: "/goods",
    currentRole: "分野別の安全用品・アフィリエイト導線",
    tier: 2,
    role: "practical-support",
    reason: "現場支援と収益化に寄与するが、製品選定の最終判断を担わないから。",
    userValue: "用途とカテゴリから安全用品候補を探し、販売先へ進める。",
    dataSource: "編集済みの商品情報と外部販売リンク。",
    aiApiIntegration: "サイト内分類。価格・在庫の正確性をAIで保証しない。",
    operationalStatus: "limited",
    operationalReadiness: "アフィリエイト表示と購入前の規格確認が必要。",
    seoValue: "安全用品・保護具の検索需要と収益価値がある。",
    safetyRisk: "適合規格・現場条件・在庫を断定せず、広告を明示する。",
    navPlacement: "全機能メニューと関連安全ページ下部。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "商品導線であり自動化サンプル扱いにしない。",
    action: "カテゴリ・規格確認・広告表示を先に見せる。",
    acceptanceCriteria: "ホームから2クリック以内、広告・規格確認・外部遷移を明示。",
    searchGroup: "tool",
    searchable: true,
    keywords: ["安全グッズ", "安全用品", "保護具", "アフィリエイト"],
  },
  {
    id: "role-construction",
    label: "建設業の安全入口",
    route: "/for/construction",
    currentRole: "現場監督・職長向けの役割別ハブ",
    tier: 2,
    role: "practical-support",
    reason: "主力機能を利用者の立場で束ね、迷いを減らす補助入口だから。",
    userValue: "今日の安全、KY、法令、記録へ立場別の順序で進める。",
    dataSource: "サイト内の公開機能と編集済み役割別導線。",
    aiApiIntegration: "サイト内リンク集約。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。",
    seoValue: "建設業・職長・現場監督の役割検索に価値がある。",
    safetyRisk: "業種一般論を個別現場判断の代替にしない。",
    navPlacement: "ホーム「役割から探す」。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "役割別導線でありサンプル扱いにしない。",
    action: "代表3タスクを先に表示。",
    acceptanceCriteria: "ホームから1クリック、主力機能へ追加1クリック以内。",
    searchGroup: "tool",
    searchable: true,
    keywords: ["建設業", "職長", "現場監督", "施工管理"],
  },
  {
    id: "role-solo",
    label: "一人親方の安全入口",
    route: "/for/solo",
    currentRole: "一人親方向けの役割別ハブ",
    tier: 2,
    role: "practical-support",
    reason: "一人KY・資格・公的情報を利用者の立場で束ねる補助入口だから。",
    userValue: "一人で確認すべき今日のリスク、KY、資格、公的資料へ進める。",
    dataSource: "サイト内公開機能と編集済み役割別導線。",
    aiApiIntegration: "サイト内リンク集約。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。",
    seoValue: "一人親方・個人事業主の明確な検索需要がある。",
    safetyRisk: "労災特別加入等を個別法務判断として断定しない。",
    navPlacement: "ホーム「役割から探す」。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "役割別導線でありサンプル扱いにしない。",
    action: "代表3タスクを先に表示。",
    acceptanceCriteria: "ホームから1クリック、主力機能へ追加1クリック以内。",
    searchGroup: "tool",
    searchable: true,
    keywords: ["一人親方", "個人事業主", "一人KY", "特別加入"],
  },
  {
    id: "role-manager",
    label: "安全衛生担当者の入口",
    route: "/for/manager",
    currentRole: "企業の安全衛生担当者向けハブ",
    tier: 2,
    role: "practical-support",
    reason: "法改正・資格・記録・事故を担当業務の順で束ねる補助入口だから。",
    userValue: "担当者が日常確認と制度対応の主要機能へ短く進める。",
    dataSource: "サイト内公開機能と編集済み役割別導線。",
    aiApiIntegration: "サイト内リンク集約。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。",
    seoValue: "安全衛生担当・総務・人事の役割検索に価値がある。",
    safetyRisk: "一般案内を会社固有の法務判断の代替にしない。",
    navPlacement: "ホーム「役割から探す」。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "役割別導線でありサンプル扱いにしない。",
    action: "代表3タスクを先に表示。",
    acceptanceCriteria: "ホームから1クリック、主力機能へ追加1クリック以内。",
    searchGroup: "tool",
    searchable: true,
    keywords: ["安全衛生担当", "総務", "人事", "安全委員会"],
  },
  {
    id: "role-consultant",
    label: "専門家の安全情報入口",
    route: "/for/consultant",
    currentRole: "労働安全コンサルタント等の専門家向けハブ",
    tier: 2,
    role: "practical-support",
    reason: "一次資料・事故・化学物質・記録を専門家の順序で束ねる補助入口だから。",
    userValue: "原文とデータへ素早く横断できる。",
    dataSource: "サイト内公開機能と編集済み役割別導線。",
    aiApiIntegration: "サイト内リンク集約。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。",
    seoValue: "専門家の職種名検索と信頼導線に価値がある。",
    safetyRisk: "サイト情報を個別助言や監修済み成果物と誤認させない。",
    navPlacement: "ホーム「役割から探す」。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "役割別導線でありサンプル扱いにしない。",
    action: "一次資料検索を最初に表示。",
    acceptanceCriteria: "ホームから1クリック、主力データへ追加1クリック以内。",
    searchGroup: "tool",
    searchable: true,
    keywords: ["労働安全コンサルタント", "社労士", "専門家", "顧問"],
  },
  {
    id: "quality-and-sources",
    label: "品質・出典",
    route: "/about/quality",
    relatedRoutes: ["/about/data-sources", "/safety-ai"],
    currentRole: "情報品質・出典・AI境界の説明",
    tier: 2,
    role: "practical-support",
    reason: "主力機能の正確性と信頼を検証可能にする横断的な証拠ページだから。",
    userValue: "どの情報が公式・編集・AI・架空の学習例か、更新方法と限界を確認できる。",
    dataSource: "運用ポリシー、データソース一覧、検証状態。",
    aiApiIntegration: "AI利用範囲と停止中機能を公開。",
    operationalStatus: "operational",
    operationalReadiness: "公開運用中。測定可能な品質と出典を説明。",
    seoValue: "直接流入よりE-E-A-Tと利用者の信頼形成に重要。",
    safetyRisk: "監修・公式・AIの実態以上の表現をしない。",
    navPlacement: "ホーム終盤とフッター。",
    indexability: "index",
    redirectCanonical: "各URLを維持し自己canonical。",
    automationSamplePotential: "信頼基盤でありサンプル扱いにしない。",
    action: "品質指標・更新日・出典種別を短く可視化。",
    acceptanceCriteria: "ホームから2クリック以内、公式・編集・AI・架空の学習例を定義。",
    searchGroup: "tool",
    searchable: true,
    keywords: ["品質", "出典", "データソース", "AI利用方針", "更新性"],
  },

  // Tier 3: 自動化サンプル / Safety Labs
  {
    id: "automation-samples-hub",
    label: "安全業務の自動化サンプル",
    route: "/automation-examples",
    currentRole: "実験・業務改善例の集約予定ページ",
    tier: 3,
    role: "automation-sample",
    reason: "主力と試作を分離し、利用可否・外部設定・データ扱いを一か所で比較するため。",
    userValue: "試せる例と本番運用可否を見分け、自社向け相談の判断材料にできる。",
    dataSource: "ポートフォリオ正本と各デモの公開状態。",
    aiApiIntegration: "集約表示のみ。相談本文や現場情報を外部AIへ送らない。",
    operationalStatus: "preparing",
    operationalReadiness: "集約コンテンツ実装済み。ルート結線後に公開可能。",
    seoValue: "薄いデモ個別ページの量産を避け、集約ページへ価値を集中。",
    safetyRisk: "サンプルを正式な主要機能・本番導入済みサービスと誤認させない。",
    navPlacement: "全機能メニューとホーム「自動化サンプル」。一次ナビには置かない。",
    indexability: "index",
    redirectCanonical: "新規URLを自己canonical。既存デモURLは維持。",
    automationSamplePotential: "Tier 3の集約正本。",
    action: "できる・できない・必要設定・データ扱い・受付状態をカードで表示。",
    acceptanceCriteria: "全掲載例にサンプル表示があり、現在の相談手段と一致。",
    searchGroup: "automation-sample",
    searchable: true,
    keywords: ["自動化サンプル", "Safety Labs", "業務改善デモ", "試作機能"],
    automationSample: {
      displayInGallery: false,
      maturityLabel: "試作",
      canDo: ["公開中のサンプルを役割・状態付きで比較する。"],
      cannotDo: ["個別業務の本番導入や相談受付を自動で開始する。"],
      requiredSettings: ["公開ルートへのページ結線。"],
      dataHandling: "一覧表示のみ。入力データや相談本文を収集しません。",
    },
  },
  {
    id: "site-records-samples",
    label: "現場の安全記録キット",
    route: "/site-records",
    relatedRoutes: [
      "/site-records/calendar",
      "/site-records/committee",
      "/site-records/incident-report",
      "/site-records/induction",
      "/site-records/inspection",
      "/site-records/monthly",
      "/site-records/near-miss",
      "/site-records/patrol",
      "/site-records/procedure",
      "/site-records/qualifications",
    ],
    currentRole: "端末内で試せる10種の記録ツール",
    tier: 3,
    role: "automation-sample",
    reason: "帳票自動化のモデルケースとして有用だが、DB・認証・組織運用を備えないから。",
    userValue: "受入教育、巡視、点検、委員会等の記録フローをブラウザで試せる。",
    dataSource: "利用者入力、端末内保存、固定テンプレート。",
    aiApiIntegration: "ブラウザ内処理。外部AI・本番DB連携なし。",
    operationalStatus: "limited",
    operationalReadiness: "デモ利用可。多端末同期・権限・監査証跡は未提供。",
    seoValue: "個別薄ページの強調より、集約された業務改善例として価値がある。",
    safetyRisk: "端末内記録を会社の正式記録・承認基盤と誤認させない。",
    navPlacement: "自動化サンプル集約のみ。",
    indexability: "index",
    redirectCanonical: "既存URL群を維持し、集約ページからラベル付きで案内。",
    automationSamplePotential: "高い。記録業務自動化の代表例。",
    action: "主力ナビから外し、サンプル状態と機能限界を明示。",
    acceptanceCriteria: "全入口にサンプル表示、端末内保存・同期なし・正式記録非代替を明示。",
    searchGroup: "automation-sample",
    searchable: true,
    keywords: [
      "記録キット",
      "安全記録",
      "安全記録サンプル",
      "巡視記録",
      "受入教育記録",
      "帳票自動化",
    ],
    automationSample: {
      displayInGallery: true,
      maturityLabel: "サンプル",
      canDo: [
        "受入教育・巡視・点検・委員会など10種の記録画面を試す。",
        "端末内で入力・印刷の流れを確認する。",
      ],
      cannotDo: [
        "複数端末で同期する。",
        "会社の正式な承認・監査証跡を提供する。",
      ],
      requiredSettings: ["本番利用には認証、権限、共有DB、保存期間の設計が必要です。"],
      dataHandling: "入力は原則この端末内で扱います。機密情報・個人情報はサンプルへ入力しないでください。",
    },
  },
  {
    id: "organization-demo",
    label: "組織管理ダッシュボード",
    route: "/organization",
    currentRole: "多拠点管理のモック画面",
    tier: 3,
    role: "automation-sample",
    reason: "SSO・権限・DB連携がなく、実運用よりUIモデルケースの価値が高いから。",
    userValue: "拠点・部署・教育進捗を一元管理する将来像を確認できる。",
    dataSource: "画面内の明示されたモックデータ。",
    aiApiIntegration: "外部API・SSO・本番DB連携なし。",
    operationalStatus: "limited",
    operationalReadiness: "閲覧デモのみ。実データ管理不可。",
    seoValue: "主力としての検索獲得は避け、集約ページから説明する。",
    safetyRisk: "モック数値を実績・実データと誤認させない。",
    navPlacement: "自動化サンプル集約のみ。",
    indexability: "noindex-follow",
    redirectCanonical: "現在URLを維持し、noindex候補として扱う。",
    automationSamplePotential: "高い。多拠点DXの画面モデルケース。",
    action: "全画面にデモ・モック・利用不可範囲を固定表示。",
    acceptanceCriteria: "実データ・SSO・権限管理を提供中と表示しない。",
    searchGroup: "automation-sample",
    searchable: true,
    keywords: ["組織管理デモ", "多拠点ダッシュボード", "モック", "Safety Labs"],
    automationSample: {
      displayInGallery: true,
      maturityLabel: "試作",
      canDo: ["拠点・部署・教育進捗をまとめる画面イメージを見る。"],
      cannotDo: ["実データを保存する。", "SSO・権限・監査ログを利用する。"],
      requiredSettings: ["本番利用には認証、権限設計、共有DB、監査ログが必要です。"],
      dataHandling: "表示値はモックです。入力・組織データの本番保存は行いません。",
    },
  },
  {
    id: "subsidy-calculator-sample",
    label: "助成金支給額試算",
    route: "/subsidies/calculator",
    relatedRoutes: ["/subsidies"],
    currentRole: "安全投資の概算モデル",
    tier: 3,
    role: "automation-sample",
    reason: "制度利用の気づきには役立つが、最新要件や受給可否を確定できないから。",
    userValue: "安全投資に関連し得る制度と概算の考え方を試せる。",
    dataSource: "公表制度情報と固定の試算条件。",
    aiApiIntegration: "ブラウザ内試算。外部申請API連携なし。",
    operationalStatus: "limited",
    operationalReadiness: "概算サンプル。申請前に最新公募要領と窓口確認が必要。",
    seoValue: "助成金需要はあるが、制度更新の維持コストと誤認リスクが高い。",
    safetyRisk: "受給可否・支給額・申請期限を確定表示しない。",
    navPlacement: "自動化サンプル集約のみ。",
    indexability: "index",
    redirectCanonical: "既存URLを維持し、サンプル表示を追加。",
    automationSamplePotential: "高い。制度チェック自動化の例。",
    action: "概算・対象時点・できないことを先に表示。",
    acceptanceCriteria: "受給保証表現0、対象時点と公式確認先を表示。",
    searchGroup: "automation-sample",
    searchable: true,
    keywords: ["助成金試算サンプル", "補助金シミュレーション", "安全投資"],
    automationSample: {
      displayInGallery: true,
      maturityLabel: "サンプル",
      canDo: ["入力条件から制度候補と概算の考え方を確認する。"],
      cannotDo: ["受給可否・最終支給額・申請期限を確定する。"],
      requiredSettings: ["申請時は最新の公募要領と担当窓口の確認が必要です。"],
      dataHandling: "試算はブラウザ内で行います。申請情報の送信・保存は行いません。",
    },
  },
  {
    id: "construction-calculator-samples",
    label: "検証済み現場計算サンプル",
    route: "/construction-calc",
    relatedRoutes: [
      "/construction-calc/soil-volume-conversion",
      "/construction-calc/slope-ratio-convert",
      "/construction-calc/rebar-mass",
      "/construction-calc/concrete-volume",
    ],
    currentRole: "公開allowlist 4計算機の集約",
    tier: 3,
    role: "automation-sample",
    reason: "数量・換算のデモ価値はあるが、他の安全判定計算機は再検証中だから。",
    userValue: "土量・勾配表記・鉄筋質量・生コン数量の計算フローを試せる。",
    dataSource: "公開allowlistの計算式と利用者入力。",
    aiApiIntegration: "ブラウザ内の決定的計算。自由記述AI案内は公開しない。",
    operationalStatus: "limited",
    operationalReadiness: "allowlist 4件のみ利用可。他の計算機はquarantine。",
    seoValue: "具体計算需要はあるが、安全判定系の誤認防止を優先。",
    safetyRisk: "数量概算を構造・施工・法令適合の最終判断に使わせない。",
    navPlacement: "自動化サンプル集約のみ。",
    indexability: "mixed",
    redirectCanonical: "既存URLを維持。非allowlistは公開導線から隔離。",
    automationSamplePotential: "高い。入力から帳票・計算結果を返す例。",
    action: "allowlistのみ表示し、概算と最終確認先を明示。",
    acceptanceCriteria: "公開4件以外を検索・ナビへ混入させず、安全可否を断定しない。",
    searchGroup: "automation-sample",
    searchable: true,
    keywords: ["現場計算サンプル", "土量換算", "勾配換算", "鉄筋質量", "生コン数量"],
    automationSample: {
      displayInGallery: true,
      maturityLabel: "サンプル",
      canDo: ["公開allowlistの数量・換算4計算をブラウザで試す。"],
      cannotDo: ["構造安全、施工可否、法令適合を最終判定する。"],
      requiredSettings: ["本番利用では設計図書、メーカー資料、専門家確認が必要です。"],
      dataHandling: "入力値と計算はブラウザ内で扱い、外部AIへ送信しません。",
    },
  },
  {
    id: "ky-examples-sample",
    label: "KYモデルケース",
    route: "/ky-examples",
    currentRole: "架空の学習例からKYの書き方を学ぶ参考集",
    tier: 3,
    role: "automation-sample",
    reason: "教育・入力例として有用だが、現場固有KYや実在事故の記録ではないから。",
    userValue: "架空の学習例で危険の見つけ方とKY用紙への整理例を確認できる。",
    dataSource: "架空の学習用モデルケースと公的な一般原則。",
    aiApiIntegration: "サイト内テンプレート連携。外部AI送信なし。",
    operationalStatus: "limited",
    operationalReadiness: "参考利用可。現場・公式資料の確認前に転記しない。",
    seoValue: "KY例の検索需要はあるが、架空の学習例の誤認防止を優先。",
    safetyRisk: "実事故・承認済みKY・現場固有対策と誤認させない。",
    navPlacement: "KY用紙と自動化サンプル集約からの補助導線。",
    indexability: "index",
    redirectCanonical: "現在URLと自己canonicalを維持。",
    automationSamplePotential: "中程度。候補提示から帳票へつなぐモデルケース。",
    action: "架空の学習例・参考・転記前確認をカード単位で表示。",
    acceptanceCriteria: "全例に架空の学習例と表示し、現場確認と公式資料確認を促す。",
    searchGroup: "automation-sample",
    searchable: true,
    keywords: ["KYモデルケース", "KY例", "架空の学習例", "KYサンプル"],
    automationSample: {
      displayInGallery: true,
      maturityLabel: "サンプル",
      canDo: ["架空の学習例で危険の整理とKY用紙への展開例を見る。"],
      cannotDo: ["実在事故を再現する。", "現場固有のKYや承認を代替する。"],
      requiredSettings: ["利用時は現場条件と公式資料を人が確認してください。"],
      dataHandling: "固定の架空教材を表示し、相談本文や現場情報を収集しません。",
    },
  },

  // Tier 4: 統合・非表示・noindex候補
  {
    id: "general-elearning",
    label: "一般Eラーニング",
    route: "/e-learning",
    relatedRoutes: ["/education", "/education/hazard-slides", "/education/pack"],
    currentRole: "旧教材・クイズ・スライド群",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "一次資料と法定科目の再検証が未完了で、検証済み一般公開テーマが0件だから。",
    userValue: "再検証完了までは安全な利用価値を提供できない。",
    dataSource: "旧編集教材。再検証待ち。",
    aiApiIntegration: "外部生成AI live評価を行わない。",
    operationalStatus: "quarantined",
    operationalReadiness: "公開停止・noindex。正式な法定教育、受講記録、修了証を提供しない。",
    seoValue: "薄い・停止中ページの検索獲得は行わない。",
    safetyRisk: "法定教育や修了証を提供中と誤認させるリスクが高い。",
    navPlacement: "主力ナビ・検索・サンプル一覧から除外。",
    indexability: "noindex-follow",
    redirectCanonical: "URLは維持し、再検証後に教育資料または資格ページへ統合判断。",
    automationSamplePotential: "安全内容が未検証のためサンプルにも掲載しない。",
    action: "quarantine継続。再検証なしに再公開しない。",
    acceptanceCriteria: "検索・sitemap・主力導線から0件、法定教育提供の誤表示0。",
    searchGroup: "education",
    searchable: false,
    keywords: ["Eラーニング停止", "教材再検証"],
  },
  {
    id: "ai-risk-prediction",
    label: "AIリスク予測",
    route: "/risk-prediction",
    currentRole: "旧自由記述リスク提案",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "安全判断の根拠・検証可能性が不足し、今日の安全と役割が重複するから。",
    userValue: "現在は安全に提供できる独立価値がない。",
    dataSource: "旧候補ロジック。",
    aiApiIntegration: "自由記述AI案内は公開しない。",
    operationalStatus: "quarantined",
    operationalReadiness: "公開隔離。",
    seoValue: "今日の安全へ意図を統合する方が検索品質を保てる。",
    safetyRisk: "生成候補を現場の安全判断と誤認するリスクが高い。",
    navPlacement: "非表示。",
    indexability: "noindex-follow",
    redirectCanonical: "将来は /risk への統合・301を検討。現時点はURL維持。",
    automationSamplePotential: "安全ロジック未検証のためサンプル掲載不可。",
    action: "quarantine継続し、今日の安全へ役割統合。",
    acceptanceCriteria: "ナビ・検索・sitemap混入0。",
    searchGroup: "tool",
    searchable: false,
    keywords: ["AIリスク予測停止"],
  },
  {
    id: "work-environment-measurement",
    label: "作業環境測定判定",
    route: "/work-environment-measurement",
    relatedRoutes: [
      "/work-environment-measurement/target-finder",
      "/work-environment-measurement/management-class-judge",
    ],
    currentRole: "旧対象判定・管理区分計算",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "法令・測定条件・計算結果の独立再検証が完了していないから。",
    userValue: "再検証完了までは安全な判定価値を提供できない。",
    dataSource: "旧法令・計算ロジック。",
    aiApiIntegration: "決定的計算だが検証完了前は非公開。",
    operationalStatus: "quarantined",
    operationalReadiness: "公開隔離。",
    seoValue: "高い検索需要より誤判定防止を優先。",
    safetyRisk: "測定義務・管理区分を誤判定する影響が大きい。",
    navPlacement: "非表示。",
    indexability: "noindex-follow",
    redirectCanonical: "URL維持。検証後に化学物質RA配下へ統合を検討。",
    automationSamplePotential: "安全ロジック未検証のため掲載不可。",
    action: "quarantine継続。",
    acceptanceCriteria: "ナビ・検索・sitemap混入0。",
    searchGroup: "chemical",
    searchable: false,
    keywords: ["作業環境測定停止"],
  },
  {
    id: "annual-plan-generator",
    label: "年次安全衛生計画ジェネレーター",
    route: "/strategy/plan-generator",
    currentRole: "旧年次計画テンプレート生成",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "業種・規模別テンプレートの根拠と適用範囲の再検証が未完了だから。",
    userValue: "再検証後は帳票自動化例になり得る。",
    dataSource: "旧編集テンプレート。",
    aiApiIntegration: "ローカル文書生成。検証前は非公開。",
    operationalStatus: "quarantined",
    operationalReadiness: "公開隔離。",
    seoValue: "一般説明は品質ページへ統合し、薄い生成ページを増やさない。",
    safetyRisk: "雛形を会社の承認済み計画・法令適合と誤認するリスク。",
    navPlacement: "非表示。",
    indexability: "noindex-follow",
    redirectCanonical: "URL維持。再検証後にTier 3化を再評価。",
    automationSamplePotential: "再検証完了後は高い。現時点は掲載不可。",
    action: "quarantine継続。",
    acceptanceCriteria: "ナビ・検索・sitemap混入0。",
    searchGroup: "automation-sample",
    searchable: false,
    keywords: ["年次計画停止"],
  },
  {
    id: "health-checkup-scheduler",
    label: "健康診断スケジューラ",
    route: "/health-checkup-scheduler",
    currentRole: "旧健診要否・日程候補判定",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "法令条件と健康情報を扱う高リスク機能で、再検証が完了していないから。",
    userValue: "現在は安全な個別判定価値を提供できない。",
    dataSource: "旧法令条件・利用者入力。",
    aiApiIntegration: "個別健康情報を外部AIへ送らない。",
    operationalStatus: "quarantined",
    operationalReadiness: "公開隔離。",
    seoValue: "検索需要より健康・法務誤認の防止を優先。",
    safetyRisk: "健診義務の誤判定や健康情報漏えいの影響が大きい。",
    navPlacement: "非表示。",
    indexability: "noindex-follow",
    redirectCanonical: "URL維持。公的ガイドへの静的統合を検討。",
    automationSamplePotential: "健康情報を扱うためサンプル掲載不可。",
    action: "quarantine継続。",
    acceptanceCriteria: "ナビ・検索・sitemap混入0、健康情報送信0。",
    searchGroup: "tool",
    searchable: false,
    keywords: ["健診スケジューラ停止"],
  },
  {
    id: "mental-health-tools",
    label: "メンタルヘルス管理",
    route: "/mental-health-management",
    relatedRoutes: ["/mental-health"],
    currentRole: "旧メンタルヘルス判定・管理機能",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "健康情報・相談・個別判断を扱う境界が未整備だから。",
    userValue: "公的相談先への静的案内以外は現在提供しない。",
    dataSource: "旧編集情報。",
    aiApiIntegration: "相談本文・健康情報のAI送信禁止。",
    operationalStatus: "quarantined",
    operationalReadiness: "公開隔離。",
    seoValue: "公的情報への案内ページへ統合する方が適切。",
    safetyRisk: "危機相談の誤受付、健康情報漏えい、軽薄な表現のリスク。",
    navPlacement: "非表示。",
    indexability: "noindex-follow",
    redirectCanonical: "URL維持。公的相談先案内への統合を検討。",
    automationSamplePotential: "掲載不可。",
    action: "quarantine継続。",
    acceptanceCriteria: "ナビ・検索・sitemap混入0、相談受付の誤表示0。",
    searchGroup: "tool",
    searchable: false,
    keywords: ["メンタルヘルス機能停止"],
  },
  {
    id: "asbestos-tools",
    label: "石綿対応支援",
    route: "/asbestos-management",
    currentRole: "旧石綿判定・書類生成",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "高リスク法令判断と書類生成の再検証が未完了だから。",
    userValue: "現在は公式資料への案内以外を提供しない。",
    dataSource: "旧法令条件・編集テンプレート。",
    aiApiIntegration: "判定・書類生成は公開しない。",
    operationalStatus: "quarantined",
    operationalReadiness: "公開隔離。",
    seoValue: "公式資料ガイドへ意図を統合する方が安全。",
    safetyRisk: "事前調査・届出義務の誤判定は影響が大きい。",
    navPlacement: "非表示。",
    indexability: "noindex-follow",
    redirectCanonical: "URL維持。公式資料ガイドへの統合を検討。",
    automationSamplePotential: "安全ロジック未検証のため掲載不可。",
    action: "quarantine継続。",
    acceptanceCriteria: "ナビ・検索・sitemap混入0。",
    searchGroup: "chemical",
    searchable: false,
    keywords: ["石綿支援停止"],
  },
  {
    id: "accident-analytics",
    label: "事故分析レポート・統計",
    route: "/accidents-reports",
    relatedRoutes: ["/accidents-analytics"],
    currentRole: "旧事故集計・分析画面",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "出典粒度と集計定義の再検証が未完了で、事故ニュースと役割が重複するから。",
    userValue: "再検証後は事故ニュースの補助分析になり得る。",
    dataSource: "旧事故データ集計。",
    aiApiIntegration: "サイト内集計。",
    operationalStatus: "redirected",
    operationalReadiness: "事故検索へ統合・リダイレクト。",
    seoValue: "検索意図を事故ニュース・事故事例へ統合。",
    safetyRisk: "集計値を公式統計・確定値と誤認させるリスク。",
    navPlacement: "非表示。",
    indexability: "redirect",
    redirectCanonical: "/accidents への既存リダイレクトを維持し、将来 /accident-news 統合を検討。",
    automationSamplePotential: "出典再検証前は掲載不可。",
    action: "既存リダイレクトと非表示を維持。",
    acceptanceCriteria: "重複index 0、検索・ナビから旧URLを案内しない。",
    searchGroup: "accident",
    searchable: false,
    keywords: ["事故分析統合"],
  },
  {
    id: "industry-portals",
    label: "旧業種別ポータル",
    route: "/industries",
    currentRole: "10業種の旧集約ページ群",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "薄い反復ページと未検証の安全ロジックが多く、役割別入口と重複するから。",
    userValue: "代表利用者の役割別入口へ統合した方が迷いが少ない。",
    dataSource: "旧編集コンテンツ。",
    aiApiIntegration: "サイト内関連付け。",
    operationalStatus: "quarantined",
    operationalReadiness: "公開隔離。",
    seoValue: "薄い業種ページ量産を避け、役割別入口と主力機能へ集約。",
    safetyRisk: "業種一般論を現場固有対策と誤認させるリスク。",
    navPlacement: "非表示。役割別入口へ置換。",
    indexability: "mixed",
    redirectCanonical: "被リンク確認後に役割別・主力ページへの個別統合を判断。",
    automationSamplePotential: "掲載不可。",
    action: "quarantine継続し、リンク価値を役割別入口へ移す。",
    acceptanceCriteria: "主力ナビ・検索・sitemap混入0、被リンクを壊す一括削除なし。",
    searchGroup: "tool",
    searchable: false,
    keywords: ["業種別ポータル統合"],
  },
  {
    id: "faq",
    label: "旧FAQ",
    route: "/faq",
    currentRole: "旧法令・安全Q&A",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "根拠・対象時点の再検証が未完了で、法令AI・用語集と重複するから。",
    userValue: "検証済み内容は将来、法令AI・用語集へ統合可能。",
    dataSource: "旧編集Q&A。",
    aiApiIntegration: "法令検索との関連付け候補。",
    operationalStatus: "quarantined",
    operationalReadiness: "公開隔離。",
    seoValue: "薄いFAQを増やさず、検証済み原文検索へ集中。",
    safetyRisk: "古い・根拠不明の回答を法的助言と誤認させるリスク。",
    navPlacement: "非表示。",
    indexability: "noindex-follow",
    redirectCanonical: "URL維持。検証済み項目のみ法令AI・用語集へ統合。",
    automationSamplePotential: "掲載不可。",
    action: "quarantine継続。",
    acceptanceCriteria: "ナビ・検索・sitemap混入0。",
    searchGroup: "law",
    searchable: false,
    keywords: ["FAQ停止"],
  },
  {
    id: "safety-signs",
    label: "旧安全標識DB",
    route: "/safety-signs",
    currentRole: "旧標識・推奨セットDB",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "JIS・法令・指針・独自推奨の境界が未検証だから。",
    userValue: "検証完了までは公的資料・製品規格の確認先を優先する。",
    dataSource: "旧標識データ。",
    aiApiIntegration: "サイト内検索。",
    operationalStatus: "quarantined",
    operationalReadiness: "全件公開隔離。",
    seoValue: "未検証標識の検索獲得を行わない。",
    safetyRisk: "設置義務・JIS適合・推奨を混同するリスク。",
    navPlacement: "非表示。",
    indexability: "noindex-follow",
    redirectCanonical: "URL維持。検証後に資料または安全グッズへ統合判断。",
    automationSamplePotential: "安全内容未検証のため掲載不可。",
    action: "quarantine継続。",
    acceptanceCriteria: "ナビ・検索・sitemap混入0。",
    searchGroup: "tool",
    searchable: false,
    keywords: ["安全標識停止"],
  },
  {
    id: "articles-empty-hub",
    label: "解説記事一覧",
    route: "/articles",
    currentRole: "公開済み記事0件の一覧",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "公開記事0件の空ハブは単独の検索価値がなく、主力新着と重複するから。",
    userValue: "公開記事がない間は新着情報・法改正・公的資料の方が有用。",
    dataSource: "公開条件を通過した記事索引。",
    aiApiIntegration: "静的索引。",
    operationalStatus: "limited",
    operationalReadiness: "空状態。公開済み記事が増えるまで主力導線にしない。",
    seoValue: "空ハブのindex価値はない。",
    safetyRisk: "内容がないのに充実した記事媒体と誤認させる。",
    navPlacement: "非表示。",
    indexability: "noindex-follow",
    redirectCanonical: "URL維持。記事公開後に再評価。",
    automationSamplePotential: "掲載不可。",
    action: "公開記事0件の間はnoindex候補。",
    acceptanceCriteria: "主力ナビから除外、公開記事数と表示主張が一致。",
    searchGroup: "education",
    searchable: false,
    keywords: ["記事一覧空状態"],
  },
  {
    id: "legacy-feature-marketing",
    label: "旧機能紹介サブページ",
    route: "/features/comparison",
    relatedRoutes: [
      "/features/quick-tour",
      "/features/use-cases",
      "/features/print",
      "/pricing",
      "/leaflet",
    ],
    currentRole: "旧比較・ツアー・用途・印刷・料金紹介",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "機能紹介が分散し、現在の運用状態と不一致になりやすいから。",
    userValue: "全機能一覧と自動化相談へ統合した方が最新状態を理解しやすい。",
    dataSource: "旧マーケティング文面。",
    aiApiIntegration: "なし。",
    operationalStatus: "quarantined",
    operationalReadiness: "公開隔離または統合候補。",
    seoValue: "重複する検索意図を /features と /services/automation へ集約。",
    safetyRisk: "停止中機能・料金・提供状態の古い主張を露出するリスク。",
    navPlacement: "非表示。",
    indexability: "mixed",
    redirectCanonical: "被リンク確認後、/features または /services/automation へ個別301を検討。",
    automationSamplePotential: "旧ページ自体は掲載せず、検証済み例だけ集約へ移す。",
    action: "新規導線を止め、統合先をページ単位で決める。",
    acceptanceCriteria: "停止中機能を利用可能と表示せず、被リンクを一括破棄しない。",
    searchGroup: "tool",
    searchable: false,
    keywords: ["旧機能紹介統合"],
  },
  {
    id: "newsletter",
    label: "メールマガジン",
    route: "/newsletter",
    currentRole: "旧メール購読ページ",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "実メール配信を行わない現在状態とページ上の定期配信主張が一致しないから。",
    userValue: "利用可能なRSS・画面通知へ統合する方が確実。",
    dataSource: "サイト内更新情報。",
    aiApiIntegration: "実メール送信なし。",
    operationalStatus: "preparing",
    operationalReadiness: "配信基盤準備中。実送信不可。",
    seoValue: "通知設定へ検索意図を統合。",
    safetyRisk: "毎週配信中・登録受付中と誤表示するリスク。",
    navPlacement: "非表示。通知ページへ統合。",
    indexability: "noindex-follow",
    redirectCanonical: "状態表示を是正後、/notifications への301を検討。",
    automationSamplePotential: "配信デモにできるが、実配信を誤認させるため現時点は掲載しない。",
    action: "新規導線を止め、通知設定へ統合。",
    acceptanceCriteria: "実メール送信0、受付中・定期配信中の虚偽表示0。",
    searchGroup: "automation-sample",
    searchable: false,
    keywords: ["メール配信準備中"],
  },
  {
    id: "lms-prelaunch",
    label: "組織LMS",
    route: "/lms",
    currentRole: "先行登録・開発前のLMS画面",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "認証・組織管理・受講記録・修了証の本番基盤が未提供だから。",
    userValue: "現在は正式な学習管理価値を提供できない。",
    dataSource: "モック・開発前UI。",
    aiApiIntegration: "本番DB・SSO・外部LMS連携なし。",
    operationalStatus: "preparing",
    operationalReadiness: "pre-launch、noindex,nofollow。",
    seoValue: "リリース前は検索獲得しない。",
    safetyRisk: "正式な受講記録・修了証・組織管理を利用可能と誤認させる。",
    navPlacement: "非表示。",
    indexability: "noindex-follow",
    redirectCanonical: "canonicalなしを維持し、実装完了後に再評価。",
    automationSamplePotential: "組織デモに統合し、LMS単独では掲載しない。",
    action: "pre-launch隔離を維持。",
    acceptanceCriteria: "検索・sitemap・主力導線から0件、提供中の誤表示0。",
    searchGroup: "education",
    searchable: false,
    keywords: ["LMS準備中"],
  },
  {
    id: "external-api-roadmap",
    label: "外部API",
    route: "/api-docs",
    currentRole: "未提供APIのロードマップ",
    tier: 4,
    role: "integrated-or-hidden",
    reason: "外部向けAPI・Webhook・SSO/SCIMが未提供で、実機能ではないから。",
    userValue: "現状説明のみで、利用可能なAPI価値は提供しない。",
    dataSource: "内部ロードマップ。",
    aiApiIntegration: "外部APIなし。",
    operationalStatus: "preparing",
    operationalReadiness: "noindex,nofollow。内部Route Handlerのみ。",
    seoValue: "未提供機能の検索獲得は行わない。",
    safetyRisk: "公開APIや連携サービスを利用可能と誤認させる。",
    navPlacement: "非表示。",
    indexability: "noindex-follow",
    redirectCanonical: "canonicalなしを維持。",
    automationSamplePotential: "実装がないため掲載しない。",
    action: "ロードマップ隔離を維持。",
    acceptanceCriteria: "検索・sitemap・主力導線から0件、API提供中の誤表示0。",
    searchGroup: "automation-sample",
    searchable: false,
    keywords: ["外部API未提供"],
  },
] as const satisfies readonly FeaturePortfolioEntry[];

// `as const`で個別値を検証しつつ、検索ヘルパーでは共通interfaceとして扱う。
const PORTFOLIO_ENTRIES: readonly FeaturePortfolioEntry[] = FEATURE_PORTFOLIO;

/** URLのクエリ・ハッシュ・末尾スラッシュを除いた比較用パス。 */
export function normalizePortfolioRoute(href: string): string {
  const path = href.trim().split(/[?#]/, 1)[0] || "/";
  if (path === "/") return path;
  return path.replace(/\/+$/, "");
}

export function getPortfolioFeatureByRoute(
  href: string,
): FeaturePortfolioEntry | undefined {
  const route = normalizePortfolioRoute(href);
  const exact = PORTFOLIO_ENTRIES.find(
    (feature) => normalizePortfolioRoute(feature.route) === route,
  );
  if (exact) return exact;
  return PORTFOLIO_ENTRIES.find((feature) =>
    feature.relatedRoutes?.some(
      (related) => normalizePortfolioRoute(related) === route,
    ),
  );
}

export function getSearchablePortfolioFeatures(): FeaturePortfolioEntry[] {
  return PORTFOLIO_ENTRIES.filter(
    (feature) => feature.searchable && feature.tier !== 4,
  );
}

export function getAutomationSamples(): FeaturePortfolioEntry[] {
  return PORTFOLIO_ENTRIES.filter(
    (feature) =>
      feature.tier === 3 &&
      feature.role === "automation-sample" &&
      feature.automationSample?.displayInGallery,
  );
}

export function getFeaturePortfolioLabels(feature: FeaturePortfolioEntry): {
  tier: string;
  role: string;
  status: string;
  searchGroup: string;
} {
  return {
    tier: FEATURE_TIER_LABELS[feature.tier],
    role: FEATURE_ROLE_LABELS[feature.role],
    status: FEATURE_STATUS_LABELS[feature.operationalStatus],
    searchGroup: FEATURE_SEARCH_GROUP_LABELS[feature.searchGroup],
  };
}
