import { NETIS_WAVE2_SOURCE_URL, type Wave2Technology } from "./netis-wave2-data";

/**
 * 国交省中国地方整備局「NETIS推奨技術等一覧」2026年4月版の番号・名称・副題と
 * 提供元の一次資料を照合。現行の個別登録状態と導入条件は導入前にNETISで再確認する。
 * 技術固有の画像の転載許諾は未確認のため、画像は掲載しない。
 */
function sourceBasis(page: number) {
  return `2026年4月公式一覧掲載（p.${page}）／9月現行NETIS個別状態未確認`;
}

export const NETIS_WAVE3_TECHNOLOGIES: readonly Wave2Technology[] = [
  {
    categoryIds: ["wave2-survey"], primaryPurpose: "efficiency",
    name: "ドローンLidarシステムTDOT",
    registrationNumber: "KK-200034", sourceRegistrationNumber: "KK-200034-VE", sourcePage: 4,
    sourceWorkType: "河川海岸", sourceSelection: "令和5年度 推奨技術", provider: "株式会社アミューズワンセルフ",
    summary: "UAV搭載レーザーで現場の地形を3次元計測します。",
    mechanism: "UAVに搭載したレーザースキャナーで地表を計測し、点群を取得します。",
    useCase: "広い法面や河川周辺の地形把握と3次元測量。",
    limitations: "飛行許可、地形・植生、測量精度、機種構成と天候を確認します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(4),
    providerSourceUrl: "https://amuse-oneself.com/service/tdotgreen/validation_sea",
  },
  {
    categoryIds: ["wave2-mechanization"], primaryPurpose: "efficiency",
    name: "ICT対応型スラリー揺動撹拌工（WILL-i工法）",
    registrationNumber: "QS-210018", sourceRegistrationNumber: "QS-210018-VE", sourcePage: 2,
    sourceWorkType: "共通工", sourceSelection: "令和8年度 準推奨技術", provider: "三信建設工業株式会社",
    summary: "地盤改良の施工位置と履歴をICTで管理します。",
    mechanism: "特殊な撹拌翼で固化材と土を混合し、GNSS位置情報で施工履歴を管理します。",
    useCase: "中層地盤改良の施工管理と履歴の確認。",
    limitations: "対象土質、改良深度、配合、GNSS精度と施工管理基準を確認します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(2),
    providerSourceUrl: "https://www.sanshin-corp.co.jp/will-method/",
  },
  {
    categoryIds: ["wave2-mechanization"], primaryPurpose: "efficiency",
    name: "建設用3Dプリンティング",
    registrationNumber: "KT-230174", sourceRegistrationNumber: "KT-230174-VE", sourcePage: 1,
    sourceWorkType: "共通工", sourceSelection: "令和7年度 推奨技術", provider: "株式会社Polyuse",
    summary: "3次元図面からモルタルを積層造形します。",
    mechanism: "3次元図面データを造形経路に変換し、モルタルを積み重ねて部材を作ります。",
    useCase: "曲線などの形状を持つコンクリート部材の製作。",
    limitations: "材料・寸法・強度、造形環境、品質管理と対象構造物への適用条件を確認します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(1),
    providerSourceUrl: "https://polyuse.xyz/",
  },
  {
    categoryIds: ["wave2-mechanization"], primaryPurpose: "efficiency",
    name: "急傾斜法面対応の遠隔操作草刈機「神刈」",
    registrationNumber: "SK-210005", sourceRegistrationNumber: "SK-210005-VE", sourcePage: 4,
    sourceWorkType: "河川維持", sourceSelection: "令和7年度 準推奨技術", provider: "株式会社アテックス",
    summary: "斜面の草刈りを離れた位置から操作します。",
    mechanism: "重量物を斜面の山側へ自動傾動し、無線遠隔操作で草刈りします。",
    useCase: "道路・河川の急傾斜法面の除草。",
    limitations: "傾斜角45度まで。25度以上は等高線方向に限定し、飛散物・視認範囲・無線状態を確認します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(4),
    providerSourceUrl: "https://atexnet.co.jp/wp-content/uploads/2024/06/247b129803f1d10de411a034f5850428.pdf",
  },
  {
    categoryIds: ["wave2-mechanization"], primaryPurpose: "efficiency",
    name: "鋼製支保工建込ロボット「ROBO ARCH」",
    registrationNumber: "KT-230301", sourceRegistrationNumber: "KT-230301-A", sourcePage: 5,
    sourceWorkType: "トンネル工", sourceSelection: "令和6年度 推奨技術", provider: "古河ロックドリル株式会社",
    summary: "トンネル切羽での鋼製支保工建込みを機械化します。",
    mechanism: "機械が鋼製支保工を把持・位置調整して建て込みを支援します。",
    useCase: "山岳トンネルの鋼製支保工建込み。",
    limitations: "トンネル断面、支保工仕様、機械の作業範囲と切羽の安全管理を確認します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(5),
    providerSourceUrl: "https://www.furukawakk.co.jp/info/2024/20241010_post_142.html",
  },
  {
    categoryIds: ["wave2-mechanization"], primaryPurpose: "efficiency",
    name: "ロックボルト施工機「ボルティンガー」",
    registrationNumber: "KT-220225", sourceRegistrationNumber: "KT-220225-A", sourcePage: 5,
    sourceWorkType: "トンネル工", sourceSelection: "令和6年度 推奨技術", provider: "古河ロックドリル株式会社",
    summary: "トンネルのロックボルト穿孔・挿入・設置を機械化します。",
    mechanism: "機械のユニットで穿孔からロックボルト設置までを行います。",
    useCase: "山岳トンネルのロックボルト施工。",
    limitations: "地山、ボルト仕様、施工位置、機械の作業範囲と切羽の安全管理を確認します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(5),
    providerSourceUrl: "https://www.furukawakk.co.jp/info/2023/20230405_netis.html",
  },
  {
    categoryIds: ["wave2-mechanization"], primaryPurpose: "efficiency",
    name: "ウォータージェットはつり処理工法（ジェットマスターJMK-2100）",
    registrationNumber: "CB-180013", sourceRegistrationNumber: "CB-180013-VE", sourcePage: 2,
    sourceWorkType: "共通工", sourceSelection: "令和6年度 推奨技術", provider: "第一カッター興業株式会社（共同開発者）",
    summary: "コンクリートのはつり作業を自動制御します。",
    mechanism: "自走式装置から超高圧水を噴射し、コンクリート床面をはつります。",
    useCase: "橋梁床版などの劣化部除去や打ち継ぎ面の処理。",
    limitations: "水圧・施工範囲、飛散防止、濁水処理、下地と鉄筋の状態を確認します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(2),
    providerSourceUrl: "https://www.daiichi-cutter.co.jp/technology/waterjet/jmk2100a/",
  },
  {
    categoryIds: ["wave2-roadwork"], primaryPurpose: "efficiency",
    name: "鋼製蓋縮小化工法「リフタス」",
    registrationNumber: "CB-210009", sourceRegistrationNumber: "CB-210009-VE", sourcePage: 1,
    sourceWorkType: "共通工", sourceSelection: "令和8年度 推奨技術", provider: "株式会社宝機材",
    summary: "既設の側溝や桝を生かして蓋受けを補修します。",
    mechanism: "既存の蓋受けに小さい受枠を入れ、隙間にグラウト材を充填します。",
    useCase: "道路側溝や桝の蓋受け部の修繕。",
    limitations: "既設側溝の寸法・損傷、受枠の適合、施工後の荷重条件を確認します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(1),
    providerSourceUrl: "https://www.takara-kizai.com/product/ankyo/refutasu/",
  },
  {
    categoryIds: ["wave2-quality"], primaryPurpose: "quality",
    name: "塗布量管理革命「シールdeチェッカー」",
    registrationNumber: "SK-210002", sourceRegistrationNumber: "SK-210002-VE", sourcePage: 5,
    sourceWorkType: "道路維持修繕工", sourceSelection: "令和7年度 準推奨技術", provider: "馬居化成工業株式会社",
    summary: "表面含浸材の塗布量を変色シールで確認します。",
    mechanism: "貼付したシールが表面含浸材に含まれるアルカリ成分に反応して変色します。",
    useCase: "コンクリート表面含浸材の塗布量確認。",
    limitations: "対象材料とシールの適合、貼付位置、判定基準を施工前に確認します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(5),
    providerSourceUrl: "https://umaichem.co.jp/products/sticker_de_checker.html",
  },
  {
    categoryIds: ["wave2-quality"], primaryPurpose: "quality",
    name: "Single i工法（シングルi工法）",
    registrationNumber: "HK-150004", sourceRegistrationNumber: "HK-150004-VE", sourcePage: 6,
    sourceWorkType: "調査試験", sourceSelection: "令和4年度 推奨技術", provider: "株式会社アースシフト（取扱）",
    summary: "小径の孔と内視鏡でコンクリート内部を確認します。",
    mechanism: "小径穿孔と特殊樹脂・内視鏡で内部のひび割れや空洞を記録します。",
    useCase: "コンクリート構造物のひび割れ・空洞の調査。",
    limitations: "穿孔位置、鉄筋位置、樹脂と内視鏡の適用条件、復旧方法を確認します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(6),
    providerSourceUrl: "https://www.earth-shift.co.jp/solution/182/",
  },
  {
    categoryIds: ["wave2-mechanization"], primaryPurpose: "efficiency",
    name: "パワーブレンダー工法（ICT施工）",
    registrationNumber: "QS-210068", sourceRegistrationNumber: "QS-210068-VE", sourcePage: 2,
    sourceWorkType: "共通工", sourceSelection: "令和8年度 準推奨技術", provider: "パワーブレンダー工法協会・株式会社加藤建設",
    summary: "地盤改良機の施工位置と履歴をICTで管理します。",
    mechanism: "トレンチャ式の撹拌にGNSS位置情報と施工履歴の記録を組み合わせます。",
    useCase: "中層地盤改良の施工管理と記録。",
    limitations: "対象土質、改良深度、配合とGNSS精度を確認し、品質管理基準に合わせて使います。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(2),
    providerSourceUrl: "https://www.kato-kensetu.co.jp/service/powerblender-ict/",
  },
  {
    categoryIds: ["wave2-mechanization"], primaryPurpose: "efficiency",
    name: "ICT技術を活用したエポコラム工法（epo-Live）",
    registrationNumber: "QS-210069", sourceRegistrationNumber: "QS-210069-VE", sourcePage: 2,
    sourceWorkType: "共通工", sourceSelection: "令和8年度 準推奨技術", provider: "エポコラム協会",
    summary: "深層混合処理の施工状況を離れた場所でも確認します。",
    mechanism: "施工機の情報を無線LANで端末に送り、施工状況を遠隔表示します。",
    useCase: "深層地盤改良の施工状況の確認。",
    limitations: "対象地盤、施工機・通信環境、施工管理項目と管理基準を確認します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(2),
    providerSourceUrl: "https://epo-k.jp/method/",
  },
  {
    categoryIds: ["wave2-mechanization"], primaryPurpose: "efficiency",
    name: "泥水二次処理剤自動添加システム",
    registrationNumber: "KT-180039", sourceRegistrationNumber: "KT-180039-A", sourcePage: 6,
    sourceWorkType: "シールド", sourceSelection: "令和6年度 推奨技術", provider: "株式会社タック",
    summary: "余剰泥水の性状に合わせ二次処理剤を自動添加します。",
    mechanism: "泥水の状態を計測し、処理剤の添加量を調整します。",
    useCase: "泥水式シールド工事の余剰泥水処理。",
    limitations: "泥水の性状、計測・校正、処理剤の適用と排出物の管理基準を確認します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(6),
    providerSourceUrl: "https://www.tac-co.com/engineering/registered-netis-technologies/",
  },
  {
    categoryIds: ["wave2-roadwork"], primaryPurpose: "efficiency",
    name: "冬用タイヤ自動判別システム",
    registrationNumber: "SK-190003", sourceRegistrationNumber: "SK-190003-VE", sourcePage: 7,
    sourceWorkType: "ITS関連技術", sourceSelection: "令和8年度 推奨技術", provider: "西日本高速道路エンジニアリング四国株式会社",
    summary: "走行車両の冬用タイヤ装着を画像から判別します。",
    mechanism: "走行車両のタイヤを撮影・画像解析し、判別結果を表示または音声で通知します。",
    useCase: "道路の冬用タイヤ規制時の確認作業。",
    limitations: "対象車種、走行速度30km/h以下、撮影環境、判別不能時の目視確認を用意します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(7),
    providerSourceUrl: "https://www.w-e-shikoku.co.jp/product/product-445/",
  },
  {
    categoryIds: ["wave2-quality"], primaryPurpose: "quality",
    name: "透気試験機「パーマトール」",
    registrationNumber: "QS-150029", sourceRegistrationNumber: "QS-150029-VE", sourcePage: 7,
    sourceWorkType: "調査試験", sourceSelection: "令和3年度 準推奨技術", provider: "エフティーエス株式会社",
    summary: "表層コンクリートの透気性を非破壊で測ります。",
    mechanism: "試験面に装置を密着させ、コンクリート表層の空気の通りやすさを測定します。",
    useCase: "コンクリート構造物の表層品質の確認。",
    limitations: "表面状態、含水状態、測定箇所、判定基準と機器の校正を確認します。",
    officialSourceUrl: NETIS_WAVE2_SOURCE_URL, sourceBasis: sourceBasis(7),
    providerSourceUrl: "https://www.fts-ltd.jp/product-list/permeatorrac/",
  },
];
